name: CI with Dependency Caching (Corrected)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-with-caching:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    # Corrected and simplified caching method
    # The `setup-node` action handles caching natively.
    # It automatically creates a smart cache key based on the lock file.
    - name: Set up Node.js and cache dependencies
      id: setup-node-with-cache # Give this step an ID to check its output
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        # This one line enables caching for npm
        cache: 'npm' 

    # This is the custom step to check the cache result.
    # It now correctly references the output from the setup-node step.
    - name: prime-cache-8fff81e
      run: echo "The cache prime was successful. Cache hit result: ${{ steps.setup-node-with-cache.outputs.cache-hit }}"

    # This step runs 'npm install' ONLY if the cache was a miss.
    - name: Install Dependencies if cache missed
      if: steps.setup-node-with-cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Run a command that uses dependencies
      run: echo "Dependencies are installed and ready to be used by build or test commands."